spring:
  application:
    name: url-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "tictactoe"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
flyway:
  schemas: tictactoe
  user: "tictactoe"
server:
  port: 6493