<!DOCTYPE html>
<html lang="en">
<head>
    <title>${state}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/css/base.css"/>
</head>
<body class="centerChildren">

<div class="centeredBox" style="min-height: 100%">

    <h1 style="color:#E0E1E2; display:block">${state}</h1>

    <a href="/" style="display: block">
        <button class="ui button" style="width: 200px; margin-bottom: 7px">Home</button>
    </a>

    <a href="/menu/create" style="display: block">
        <button class="ui button" style="width: 200px; margin-bottom: 7px">New Game</button>
    </a>

</div>

</body>
</html>