<!DOCTYPE html>
<html>
<head>
    <title>Saud's TicTacToe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/css/game-style-base.css"/>
</head>
<body>

${game.player1Name} vs. ${game.player2Name}

<table>
    <tr>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
    </tr>
    <tr>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
    </tr>
    <tr>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
        <td class="clickable-area"><div class="my-cell"></div></td>
    </tr>
</table>

<script src="/js/game-logic.js"></script>

</body>
</html>